"""initial schema

Revision ID: 7084f7de6077
Revises: 
Create Date: 2026-08-29 05:48:23.582536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7084f7de6077'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'RUNNING', 'FINISHED', name='tournament_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boss_battles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'FINISHED', name='boss_battle_status'), nullable=False),
    sa.Column('rank_entering_final', sa.Integer(), nullable=True),
    sa.Column('legendary_promptmon_name', sa.String(length=100), nullable=False),
    sa.Column('boss_strategy_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Enum('ROUND_2', 'ROUND_3', name='match_round'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'FINISHED', name='match_status'), nullable=False),
    sa.Column('session_a_id', sa.UUID(), nullable=False),
    sa.Column('session_b_id', sa.UUID(), nullable=False),
    sa.Column('winner_session_id', sa.UUID(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('twist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_a_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['session_b_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['winner_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promptmons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('abilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('special_attack', sa.String(length=200), nullable=False),
    sa.Column('backstory', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('creativity_score', sa.Float(), nullable=True),
    sa.Column('creativity_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('boss_battle_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('boss_battle_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('gemini_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boss_battle_id'], ['boss_battles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boss_battle_id', 'turn_number', name='uq_boss_conversation_turn')
    )
    op.create_table('boss_battle_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('boss_battle_id', sa.UUID(), nullable=False),
    sa.Column('prompt_quality', sa.Float(), nullable=False),
    sa.Column('strategy', sa.Float(), nullable=False),
    sa.Column('creativity', sa.Float(), nullable=False),
    sa.Column('adaptability', sa.Float(), nullable=False),
    sa.Column('final_battle_performance', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boss_battle_id'], ['boss_battles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boss_battle_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('gemini_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'session_id', 'turn_number', name='uq_conversation_turn')
    )
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('prompt_quality', sa.Float(), nullable=False),
    sa.Column('strategy', sa.Float(), nullable=False),
    sa.Column('adaptability', sa.Float(), nullable=False),
    sa.Column('battle_performance', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'session_id', name='uq_score_per_session_per_match')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('conversations')
    op.drop_table('boss_battle_scores')
    op.drop_table('boss_battle_conversations')
    op.drop_table('promptmons')
    op.drop_table('matches')
    op.drop_table('boss_battles')
    op.drop_table('sessions')
    op.drop_table('tournaments')
    # ### end Alembic commands ###